
# ATTENTION DEVELOPER:
#
# When this service is ready to be built and deployed along with the other microservices, the following must occur
#
# 1. Rename this file to "cre-ms-retail.yml"
# 2. Remove this comment block.
# 3. Add the file to the ssp-configuration-repo Git repository under the "ms" branch.
# 4. Start this service to confirm it obtains its configuration.
#

management.security.enabled: false
security.basic.enabled: false

server:
  port: 9222
  contextPath: /retail


---
spring:
  profiles: dev
  datasource:
      url: jdbc:mysql://localhost:11888/sspms?autoReconnect=true&tinyInt1isBit=false&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: root
      password: tenxdev
      driver-class-name: com.mysql.jdbc.Driver
      jpa:
        hibernate:
        ddl-auto: create-drop

logging.level.com.tenx.ms.gls: DEBUG
flyway.locations: classpath:db/migration
flyway.baselineOnMigrate: false
